# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - pdf
  - epub

# Build documentation from the docs/ directory
# If you don't have a docs directory yet, you can change this to root
python.install.requirements:
  - docs/requirements.txt